### ISSUE TITLE
Merge into upstream h5py?

### ISSUE THREAD

**Issue by aragilar** [moble/h5py_cache#1]
@moble h5py would welcome the improvements included in h5py_cache, it would appear relatively simple to add in the new arguments to h5py.File

**Comment by moble** [comment]
Yeah, I can start a PR over there.  Am I right in thinking that there's no testing inside `h5py`?  There are just a few simple tests I wrote for this module.

**Comment by moble** [comment]
Oh, no.  I found the tests.  Sorry.

**Comment by moble** [comment]
I've started the PR, so I'll close this issue.
